### ISSUE TITLE
[Issue] in example_dem_2d.pro

### ISSUE THREAD

**Issue by MohamedNedal** [ianan/demreg#2]
Hello, 
I was running the **example_dem_2d.pro** file and I got 2 plots and one error at `stop` before the `end `of the file: 
```
% Procedure was compiled while active: EXAMPLE_DEM_2D. Returning.
% Compiled module: EXAMPLE_DEM_2D.
      0 of    2500,   0.0%
100% Done
    674.6 DEM/s
% LOADCT: Loading table Rainbow + white
% Stop encountered: EXAMPLE_DEM_2D    105
% Program caused arithmetic error: Floating underflow
```
How can it be fixed please?

**Comment by ianan** [comment]
There is a stop at the end of the code, that's why it stopped. There is no error.

**Comment by MohamedNedal** [comment]
> There is a stop at the end of the code, that's why it stopped. There is no error.

Could you please explain what does this error mean `% Program caused arithmetic error: Floating underflow` ?

**Comment by PaulJWright** [comment]
@MohamedNedal http://www.idlcoyote.com/math_tips/underflow.html

**Comment by ianan** [comment]
Not a "real" error - nothing to worry about, fairly standard output in IDL

**Comment by MohamedNedal** [comment]
Ok, thanks a lot

**Comment by MohamedNedal** [comment]
> @MohamedNedal http://www.idlcoyote.com/math_tips/underflow.html

Thank you!
